[build]
  command = "npm ci && npm run build"
  publish = "dist"

# Fallback SPA : indispensable pour une app React/Vite
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
